import 'package:shared/models/user_mode.dart';

UserModel guestModel = UserModel(
  id: "",
  userName: "",
  phone: "",
  isVerified: false,
  role: "",
  city: "",
  age: 0,
  height: 0,
  job: "",
  description: "",
  language: "",
  isMarried: false,
  image: "",
  gender: "",
  isEngaged: false,
  isBlocked: false,
  terms: "",
  note: "",
  hasMarried: false,
  allowChat: false,
  allowKhattaba: false,
  randomSort: 0,
  isFavorite: false,
  hasValidSubscription: false,
  specification: SpecificationModel(
    height: 0,
    age: 0,
    job: "",
    beautyLevel: "",
    city: "",
    dowry: "",
    education: "",
    financialStatus: "",
    hairType: "",
    lookingFor: "",
    marriageType: "",
    nameEndsWith: "",
    nationality: "",
    skinColor: "",
    smoking: false,
    terms: "",
    weight: 0,
  ),
);

