name: shared
description: Shared widgets, styles, and models for monorepo apps.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  core:
    path: ../core
  flutter_screenutil: ^5.9.3
  fluttertoast: ^8.2.12
  intl_phone_number_input: ^0.7.4
  flutter_svg: ^2.2.0
